// <auto-generated />
using EF_Core_DbFirst_Demo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace EF_Core_DbFirst_Demo.Migrations
{
    [DbContext(typeof(vanfjContext))]
    partial class vanfjContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("EF_Core_DbFirst_Demo.Models.Userentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)");

                    b.Property<int?>("Age")
                        .HasColumnType("int(10)");

                    b.Property<string>("Phone")
                        .HasMaxLength(255);

                    b.Property<string>("Qq")
                        .HasColumnName("QQ")
                        .HasMaxLength(255);

                    b.Property<string>("UserId")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("userentity");
                });
#pragma warning restore 612, 618
        }
    }
}
